### ISSUE TITLE
Devolutiva primeiro desafio - Lógica com JS

### ISSUE THREAD

**Issue by MateusPaixao** [Rafael-GSousa/Ada_Tech-Modulo02#1]
![image](https://github.com/Rafael-GSousa/Ada_Tech-Modulo02/assets/20425031/be71d4a4-f5b9-4112-adfb-77c37d80569e)

- Chegou no resultado esperado
- Uso correto de operador de coerção
- Concatenação de string e interpolação com template string.

Dicas: 

- Utilizar nomes da variáveis mais coesas, exemplo ao invés de `md ` usar `media`.
No mais, excelente entrega parabéns. 💚🚀

**Comment by Rafael-GSousa** [comment]
Obrigado pelo feedback, Professor!

Ficarei mais atento quanto aos nomes das variáveis.
