### ISSUE TITLE
Devolutiva segundo desafio - Lógica com JS

### ISSUE THREAD

**Issue by MateusPaixao** [Rafael-GSousa/Ada_Tech-Modulo02#2]
![image](https://github.com/Rafael-GSousa/Ada_Tech-Modulo02/assets/20425031/16f226a1-ad88-4219-a0c3-267c9a74e4aa)

- Excelente uso de objeto e `arrays`
- Excelente uso do `forEach`
- Utilizou condicionais `if-else`
- Entendeu o contexto e conseguiu chegar no resultado final

No mais, excelente entrega parabéns. 💚🚀

**Comment by Rafael-GSousa** [comment]
Obrigado pelo feedback, Professor!
